import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { encodeFunctionData, keccak256, parseTransaction } from 'viem';
import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts';
import { TreasuryOperator, loadTreasuryOperator, TREASURY_OPERATOR_ARM } from '../src/treasury-operator.mjs';
import { TREASURY_RUNWAY_ABI } from '../src/runway.mjs';
import { loadFeeOperator } from '../src/fee-operator.mjs';
const owner='0x1111111111111111111111111111111111111111',treasury='0x2222222222222222222222222222222222222222',recipient='0x3333333333333333333333333333333333333333',other='0x4444444444444444444444444444444444444444',protocol='0x5555555555555555555555555555555555555555',BLOCK='0x'+'a'.repeat(64),expense='0x'+'b'.repeat(64),NOW=1800000000000;
test('disabled operators erase inherited key variables without touching key files',()=>{for(const [load,flag,key,file] of [[loadFeeOperator,'VEYL_FEE_KEEPER_ENABLED','VEYL_FEE_OPERATOR_PRIVATE_KEY','VEYL_FEE_OPERATOR_KEY_FILE'],[loadTreasuryOperator,'VEYL_AUTOMATIC_RUNWAY_ENABLED','VEYL_TREASURY_OPERATOR_PRIVATE_KEY','VEYL_TREASURY_OPERATOR_KEY_FILE']]){const env={[flag]:'false',[key]:generatePrivateKey(),[file]:'/missing/operator-only/file'};assert.equal(load({env}),null);assert.equal(Object.hasOwn(env,key),false);assert.equal(env[file],'/missing/operator-only/file');}});
function fixture(t, options={}) {
 const dir=mkdtempSync(join(tmpdir(),'veyl-treasury-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const file=join(dir,'operator.json'),account=privateKeyToAccount(generatePrivateKey());
 const data=encodeFunctionData({abi:TREASURY_RUNWAY_ABI,functionName:'pay',args:[expense,recipient,1000000n]}), project={id:'treasury-fixture',mainnet:{treasury}};
 const request={chain:{id:1},account:{address:account.address},to:treasury,data,value:0n};
 const state={persistence:'healthy',fundingAddress:recipient,policy:{projectId:project.id,treasury,owner,operator:account.address,maxTopUpWei:'1000000',dailyTopUpWei:'2000000',automatic:true},refills:[{id:randomUUID(),expenseId:expense,status:'sending',fundingAddress:recipient,amountWei:'1000000',budgetDay:String(BigInt(NOW/1000)/86400n),calls:[{chainId:'0x1',from:account.address,to:treasury,data,value:'0x0'}]}]};
 let signCount=0,sendCount=0,last,ready=false,final=9n,lost=false,gas=2n,clock=NOW,nonce=0;
 const chain={owner,operator:account.address,dailyLimit:10000000n,spentOnDay:0n,allowedRecipient:true,paid:false};
 const funding={capabilities:()=>({approvalEnabled:true}),inspect:async()=>({funding:{address:recipient}})};
 const client={getBlock:async({blockTag}={})=>({number:blockTag==='finalized'?final:10n,hash:BLOCK,timestamp:BigInt(Math.floor(clock/1000)),baseFeePerGas:1n}),readContract:async({functionName})=>chain[functionName],getBalance:async()=>100000000n,getTransactionCount:async()=>nonce,estimateFeesPerGas:async()=>({maxFeePerGas:gas,maxPriorityFeePerGas:1n}),estimateGas:async()=>100000n,
 sendRawTransaction:async({serializedTransaction})=>{sendCount++;last=parseTransaction(serializedTransaction);const hash=keccak256(serializedTransaction),saved=JSON.parse(readFileSync(file,'utf8')).entries.at(-1);assert.equal(saved.status,'broadcasting');assert.equal(saved.transactionHash,hash);if(lost)throw Error('lost response');return hash;},
 getTransactionReceipt:async({hash})=>{if(!ready)throw Error('not found');return{transactionHash:hash,blockHash:BLOCK,blockNumber:10n,status:'success',gasUsed:80000n,effectiveGasPrice:2n};},getTransaction:async()=>({...last,from:account.address,input:last.data,value:0n})};
 const markets={client,config:{},checkChain:async()=>{},validateMarket:async()=>({treasury,creator:owner,protocol})};
 const signer={address:account.address,signTransaction:async tx=>{signCount++;assert.equal(JSON.parse(readFileSync(file,'utf8')).entries.at(-1).status,'reserved');return account.signTransaction(tx);}};
 const config={file,markets,signer,enabled:true,dailyGasLimitWei:'1000000',maxFeePerGasWei:'10',maxPriorityFeePerGasWei:'3',maxGasPerTransaction:'200000',now:()=>clock,...options},operator=new TreasuryOperator(config);
 const bind=op=>op.forProject({project,funding,getRunway:()=>structuredClone(state)});
 return{operator,adapter:bind(operator),bind,config,project,state,request,client,markets,chain,funding,signer,file,counts:()=>({signCount,sendCount}),restart:()=>new TreasuryOperator(config),failSend:()=>{lost=true;},ready:()=>{ready=true;final=10n;},setGas:n=>{gas=n;},next:()=>{clock+=86400000;nonce++;}};
}
test('automatic treasury adapter is disabled by default and never reads a key',async t=>{const f=fixture(t,{enabled:false});await assert.rejects(f.adapter.sendTransaction(f.request),/disabled/);assert.equal(loadTreasuryOperator({env:{VEYL_TREASURY_OPERATOR_KEY_FILE:'/missing'}}),null);assert.deepEqual(f.counts(),{signCount:0,sendCount:0});});
test('treasury adapter persists nonce/budget before signing and hash before submission',async t=>{const f=fixture(t),hash=await f.adapter.sendTransaction(f.request);assert.match(hash,/^0x[\da-f]{64}$/);assert.equal(f.operator.snapshot().pending.status,'pending');assert.equal(f.operator.snapshot().dayReservedGasWei,'240000');assert.equal((await f.restart().recover()).recovery,'receipt-unavailable-no-replay');f.ready();assert.equal((await f.operator.recover()).status,'confirmed');assert.equal(f.operator.snapshot().dayReservedGasWei,'240000');});
test('lost RPC acceptance returns saved identity and cannot replay across restart',async t=>{const f=fixture(t);f.failSend();const hash=await f.adapter.sendTransaction(f.request);assert.equal(f.operator.snapshot().pending.status,'send_unknown');const next=f.restart();assert.equal(await f.bind(next).sendTransaction(f.request),hash);assert.deepEqual(f.counts(),{signCount:1,sendCount:1});f.ready();assert.equal((await next.recover()).status,'confirmed');});
test('signing uncertainty without hash is blocked on restart',async t=>{const f=fixture(t);f.signer.signTransaction=async()=>{throw Error('unavailable');};await assert.rejects(f.adapter.sendTransaction(f.request),error=>{assert.match(error.message,/Uncertain/);assert.equal(error.treasuryNoSigningAttempted,undefined);return true;});await assert.rejects(f.bind(f.restart()).sendTransaction(f.request),error=>{assert.match(error.message,/cannot be replayed/);assert.equal(error.treasuryNoSigningAttempted,undefined);return true;});assert.equal(f.counts().sendCount,0);});
test('different project cannot reuse a saved expense identity',async t=>{const f=fixture(t);await f.adapter.sendTransaction(f.request);const p={...f.project,id:'other-project'};f.state.policy.projectId=p.id;const adapter=f.operator.forProject({project:p,funding:f.funding,getRunway:()=>f.state});await assert.rejects(adapter.sendTransaction(f.request),/identity conflicts/);assert.equal(f.counts().sendCount,1);});
test('request and owner opt-in cannot be bypassed',async t=>{for(const change of [f=>{f.state.policy.automatic=false;},f=>{f.state.policy.projectId='other';},f=>{f.state.persistence='blocked';},f=>{f.state.refills[0].status='prepared';},f=>{f.state.refills[0].amountWei='2';},f=>{f.state.fundingAddress=other;},f=>{f.request.gas=1n;},f=>{f.request.value=1n;},f=>{f.request.chain.id=31337;}]){const f=fixture(t);change(f);await assert.rejects(f.adapter.sendTransaction(f.request));assert.equal(f.counts().signCount,0);}});
test('full market identity, current daemon recipient and live onchain permissions are required',async t=>{for(const change of [f=>{f.markets.validateMarket=async()=>{throw Error('wrong bytecode');};},f=>{f.funding.inspect=async()=>({funding:{address:other}});},f=>{f.chain.owner=other;},f=>{f.chain.operator=other;},f=>{f.chain.allowedRecipient=false;},f=>{f.chain.paid=true;},f=>{f.funding.capabilities=()=>({approvalEnabled:false});}]){const f=fixture(t);change(f);await assert.rejects(f.adapter.sendTransaction(f.request));assert.equal(f.counts().signCount,0);}});
test('per-refill, policy daily and onchain daily ceilings independently stop spending',async t=>{for(const change of [f=>{f.state.policy.maxTopUpWei='999999';},f=>{f.state.policy.dailyTopUpWei='999999';},f=>{f.chain.dailyLimit=999999n;},f=>{f.chain.spentOnDay=9500000n;}]){const f=fixture(t);change(f);await assert.rejects(f.adapter.sendTransaction(f.request),/limit/);assert.equal(f.counts().sendCount,0);}});
test('gas price, transaction gas and global daily cost are checked before signing',async t=>{for(const [options,change]of[[{dailyGasLimitWei:'239999'},()=>{}],[{maxGasPerTransaction:'119999'},()=>{}],[{},f=>f.setGas(11n)]]){const f=fixture(t,options);change(f);await assert.rejects(f.adapter.sendTransaction(f.request),error=>{assert.match(error.message,/gas|price/);assert.equal(error.treasuryNoSigningAttempted,true);return true;});assert.equal(f.counts().signCount,0);}});
test('unresolved global transaction stops a second project/expense',async t=>{const f=fixture(t);await f.adapter.sendTransaction(f.request);const id='0x'+'c'.repeat(64);f.state.refills[0].expenseId=id;f.request.data=encodeFunctionData({abi:TREASURY_RUNWAY_ABI,functionName:'pay',args:[id,recipient,1000000n]});f.state.refills[0].calls[0].data=f.request.data;await assert.rejects(f.adapter.sendTransaction(f.request),/awaits final recovery/);assert.equal(f.counts().sendCount,1);});
test('global gas reservation survives restart and resets only on the following UTC day',async t=>{const f=fixture(t,{dailyGasLimitWei:'240000'});await f.adapter.sendTransaction(f.request);f.ready();await f.operator.recover();const next=f.restart(),id='0x'+'c'.repeat(64);f.state.refills[0].expenseId=id;f.request.data=encodeFunctionData({abi:TREASURY_RUNWAY_ABI,functionName:'pay',args:[id,recipient,1000000n]});f.state.refills[0].calls[0].data=f.request.data;await assert.rejects(f.bind(next).sendTransaction(f.request),/daily gas budget/);assert.equal(f.counts().sendCount,1);f.next();await f.bind(next).sendTransaction(f.request);assert.equal(f.counts().sendCount,2);});
test('a signer that changes the saved destination cannot submit its signature',async t=>{const f=fixture(t),original=f.signer.signTransaction;f.signer.signTransaction=tx=>original({...tx,to:other});await assert.rejects(f.adapter.sendTransaction(f.request),/Uncertain treasury signing/);assert.equal(f.operator.snapshot().pending.status,'reserved');assert.equal(f.counts().sendCount,0);});
test('owner pause during awaited RPC preparation wins before any signature',async t=>{const f=fixture(t);f.client.estimateGas=async()=>{f.state.policy.automatic=false;return 100000n;};await assert.rejects(f.adapter.sendTransaction(f.request),error=>{assert.match(error.message,/authorization changed/);assert.equal(error.treasuryNoSigningAttempted,true);return true;});assert.equal(f.operator.snapshot().pending,null);assert.deepEqual(f.counts(),{signCount:0,sendCount:0});});
test('persistence failure prevents signing and separate operator identities are enforced',async t=>{const f=fixture(t);mkdirSync(f.file);await assert.rejects(f.adapter.sendTransaction(f.request));assert.equal(f.counts().signCount,0);assert.throws(()=>new TreasuryOperator({...f.config,file:join(f.file,'new.json'),forbiddenAddresses:[f.signer.address]}),/separate treasury/);});
test('secure treasury loader needs an arm and cannot sign fee calls, owner changes or ETH transfers',async()=>{const secret=generatePrivateKey(),account=privateKeyToAccount(secret),env={VEYL_AUTOMATIC_RUNWAY_ENABLED:'true',VEYL_TREASURY_OPERATOR_ADDRESS:account.address,VEYL_TREASURY_OPERATOR_PRIVATE_KEY:secret};assert.throws(()=>loadTreasuryOperator({env:{...env}}),/not explicitly armed/);const source={...env,VEYL_TREASURY_OPERATOR_ARM:TREASURY_OPERATOR_ARM},signer=loadTreasuryOperator({env:source});assert.equal(source.VEYL_TREASURY_OPERATOR_PRIVATE_KEY,undefined);assert.deepEqual(Object.keys(signer),['address','signTransaction']);const tx={type:'eip1559',chainId:1,to:treasury,data:encodeFunctionData({abi:TREASURY_RUNWAY_ABI,functionName:'pay',args:[expense,recipient,1n]}),value:0n,nonce:0,gas:100000n,maxFeePerGas:2n,maxPriorityFeePerGas:1n};assert.equal(parseTransaction(await signer.signTransaction(tx)).to,treasury);await assert.rejects(signer.signTransaction({...tx,data:encodeFunctionData({abi:TREASURY_RUNWAY_ABI,functionName:'setRecipient',args:[recipient,true]})}),/only exact pay/);await assert.rejects(signer.signTransaction({...tx,value:1n}),/non-expense/);assert.throws(()=>loadTreasuryOperator({env:{...env,VEYL_TREASURY_OPERATOR_ARM:TREASURY_OPERATOR_ARM},forbiddenAddresses:[account.address]}),/separate public/);});
